#!/usr/bin/env python
# coding: utf-8

# In[1]:


import numpy as np


# In[2]:


X = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
X = np.reshape(X, (-1,3))


# In[3]:


print(X)


# In[4]:


X[X % 2 == 1] = -1


# In[5]:


print(X)


# In[6]:


x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89])
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])


# In[7]:


mask_greater = (x > y)
mask_equal = (x == y)
positions_greater = np.where(mask_greater)[0]
positions_equal = np.where(mask_equal)[0]


# In[8]:


print(positions_greater, positions_equal)


# In[9]:


print(positions_equal)


# In[10]:


newX = np.arange(100).reshape(5, -1)


# In[11]:


print(newX[:,:4])


# In[12]:


randArr = np.random.randint(30,41, [10])


# In[13]:


print(randArr)


# In[14]:


A = np.array(([1,2,3], [4,5,6], [7,8,10]))
B = np.array(([7,8,10], [4,5,6], [1,2,3]))


# In[15]:


C = np.add(A, B)


# In[16]:


E = np.subtract(A,B)


# In[17]:


print(np.sum(A)) #sum of all elements in A
print(np.sum(B, axis = 0)) # sum of all columns in B
print(np.sum(C, axis = 1))


# In[18]:


D = np.dot(A,B)


# In[19]:


print(D)


# In[20]:


E = np.sort(C)


# In[21]:


print(E)


# In[22]:


print(np.transpose(E))





